# Generated by Django 2.1.7 on 2019-02-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
    ]
